version: 2.1
orbs:
  node: circleci/node@7.1.0
  codecov: codecov/codecov@1.1.1
executors:
  test-executor:
    docker:
      - image: cimg/node:16.14.2
jobs:
  test:
    executor: test-executor
    steps:
      - checkout
      - node/install-packages:
          cache-path: ~/rocketshoes-app/node_modules
      - run: npm run test
      - codecov/upload:
          file: tests/coverage/*.json
workflows:
  test:
    jobs:
      - test
